# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://Yue-Bu.github.io
date_format: "ordinal"
title: Lexi (Yue)'s Blog
subtitle: "Variety is the spice of life"
description: "Personal Blog"
keywords: Diary, Techonlogy, github pages, Post, North America, Leetcode, Interview
timezone: America/Nebraska
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Lexi
organization:
organization_url:
github_username: Yue-Bu
location: Nebraska, US
email: hello@lexibu.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

  -
    href: /open-source/
    label: Github Repos

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-seo-tag

repository: Yue-Bu/Yue-Bu.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: Yue-Bu
    repo: Yue-Bu.github.io
    oauth:
        client_id: ce98434bbb70a47a8a80
        client_secret: 4e331056e8b307a25ae602fdfd6e805ed9f21762
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: Yue-Bu
    repo: Yue-Bu.github.io
    clientID: ce98434bbb70a47a8a80
    clientSecret: 4e331056e8b307a25ae602fdfd6e805ed9f21762
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-113380665-1
